org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_mappings_version=26.3+build.1
loader_version=0.19.5
fabric_api_version=0.19.5+1.26.3
java_version=25

mod_id=iceandfire
mod_name=Ice And Fire Community Edition
mod_license=LGPL-3.0
mod_version=2.2-beta.3-fabric-26.3
mod_group_id=com.iafenvoy.iceandfire

geckolib_version=4.7.7
curios_version=15.0.0+26.3
